-- ============================================================
-- File: 01_create_flights_table.sql
-- Purpose:
-- Create the staging table used to receive the cleaned airline
-- flight data exported from Python.
--
-- Important:
-- This table is intentionally lightly constrained because it is
-- a staging/import table. Stronger constraints are applied later
-- when the final flights table is created.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Remove the existing staging table
-- ------------------------------------------------------------

DROP TABLE IF EXISTS flights_staging;


-- ------------------------------------------------------------
-- 2. Create the staging table
-- ------------------------------------------------------------

CREATE TABLE flights_staging (
    flight_date DATE,

    carrier_code VARCHAR(10),
    tail_number VARCHAR(20),
    flight_number INTEGER,

    origin_airport_id INTEGER,
    origin_airport VARCHAR(10),

    destination_airport_id INTEGER,
    destination_airport VARCHAR(10),

    scheduled_departure_time INTEGER,
    actual_departure_time INTEGER,

    departure_delay NUMERIC,
    departure_delay_nonnegative NUMERIC,

    scheduled_arrival_time INTEGER,
    actual_arrival_time INTEGER,

    arrival_delay NUMERIC,
    arrival_delay_nonnegative NUMERIC,

    cancelled BOOLEAN,
    cancellation_code VARCHAR(5),
    diverted BOOLEAN,

    scheduled_elapsed_time NUMERIC,
    actual_elapsed_time NUMERIC,
    air_time NUMERIC,
    distance NUMERIC,

    route VARCHAR(25),
    departure_hour INTEGER,

    is_arrival_delayed_15 BOOLEAN,
    is_departure_delayed_15 BOOLEAN
);


-- ------------------------------------------------------------
-- 3. Import the cleaned flight CSV
--
-- The cleaned dataset should be generated by:
-- python/03_clean_flights.py
--
-- In pgAdmin:
--   1. Right-click flights_staging
--   2. Select Import/Export Data
--   3. Select Import
--   4. Choose the cleaned CSV
--   5. Enable Header
--   6. Set delimiter to comma
--
-- Do not rerun the DROP TABLE and CREATE TABLE statements after
-- importing unless you intentionally want to rebuild the table.
-- ------------------------------------------------------------


-- ------------------------------------------------------------
-- 4. Create staging indexes after the import
--
-- These indexes support validation and the creation of the final
-- flights table. They should be created after loading the data,
-- because inserting millions of records is faster without them.
-- ------------------------------------------------------------

CREATE INDEX idx_flights_staging_date
ON flights_staging (flight_date);

CREATE INDEX idx_flights_staging_carrier
ON flights_staging (carrier_code);

CREATE INDEX idx_flights_staging_origin
ON flights_staging (origin_airport);

CREATE INDEX idx_flights_staging_destination
ON flights_staging (destination_airport);

CREATE INDEX idx_flights_staging_route
ON flights_staging (route);


-- ------------------------------------------------------------
-- 5. Update PostgreSQL query-planning statistics
-- ------------------------------------------------------------

ANALYZE flights_staging;


-- ------------------------------------------------------------
-- 6. Validate the staging import
-- ------------------------------------------------------------

SELECT
    COUNT(*) AS total_rows,
    MIN(flight_date) AS first_flight_date,
    MAX(flight_date) AS last_flight_date,
    COUNT(DISTINCT carrier_code) AS total_carriers,
    COUNT(DISTINCT route) AS total_routes
FROM flights_staging;


-- ------------------------------------------------------------
-- 7. Check important fields for null values
-- ------------------------------------------------------------

SELECT
    COUNT(*) FILTER (
        WHERE flight_date IS NULL
    ) AS missing_flight_dates,

    COUNT(*) FILTER (
        WHERE carrier_code IS NULL
    ) AS missing_carriers,

    COUNT(*) FILTER (
        WHERE origin_airport IS NULL
    ) AS missing_origins,

    COUNT(*) FILTER (
        WHERE destination_airport IS NULL
    ) AS missing_destinations,

    COUNT(*) FILTER (
        WHERE flight_number IS NULL
    ) AS missing_flight_numbers

FROM flights_staging;


-- ------------------------------------------------------------
-- 8. Validate selected numeric fields
-- ------------------------------------------------------------

SELECT
    COUNT(*) FILTER (
        WHERE distance < 0
    ) AS negative_distance_records,

    COUNT(*) FILTER (
        WHERE scheduled_elapsed_time < 0
    ) AS negative_scheduled_elapsed_records,

    COUNT(*) FILTER (
        WHERE actual_elapsed_time < 0
    ) AS negative_actual_elapsed_records,

    COUNT(*) FILTER (
        WHERE air_time < 0
    ) AS negative_air_time_records,

    COUNT(*) FILTER (
        WHERE departure_hour < 0
           OR departure_hour > 23
    ) AS invalid_departure_hours

FROM flights_staging;


-- ------------------------------------------------------------
-- 9. Validate derived delay fields
-- ------------------------------------------------------------

SELECT
    COUNT(*) FILTER (
        WHERE departure_delay_nonnegative < 0
    ) AS invalid_nonnegative_departure_delays,

    COUNT(*) FILTER (
        WHERE arrival_delay_nonnegative < 0
    ) AS invalid_nonnegative_arrival_delays,

    COUNT(*) FILTER (
        WHERE is_departure_delayed_15 IS TRUE
          AND departure_delay < 15
    ) AS inconsistent_departure_delay_flags,

    COUNT(*) FILTER (
        WHERE is_arrival_delayed_15 IS TRUE
          AND arrival_delay < 15
    ) AS inconsistent_arrival_delay_flags

FROM flights_staging;


-- ------------------------------------------------------------
-- 10. Preview imported records
-- ------------------------------------------------------------

SELECT *
FROM flights_staging
ORDER BY flight_date, carrier_code, flight_number
LIMIT 25;