-- ============================================================
-- File: 05_create_flight_fare_sales.sql
-- Purpose:
-- Create the PostgreSQL destination table for the synthetic
-- fare-class sales data generated by Python.
-- ============================================================


-- ------------------------------------------------------------
-- 1. Remove the existing table so the script is rerunnable
-- ------------------------------------------------------------

DROP TABLE IF EXISTS flight_fare_sales;


-- ------------------------------------------------------------
-- 2. Create the fare-sales table
-- ------------------------------------------------------------

CREATE TABLE flight_fare_sales (
    flight_id BIGINT NOT NULL,
    fare_class VARCHAR(30) NOT NULL,
    seat_capacity INTEGER NOT NULL,
    passengers INTEGER NOT NULL,
    average_fare NUMERIC(10,2) NOT NULL,
    ticket_revenue NUMERIC(14,2) NOT NULL
);


-- ------------------------------------------------------------
-- 3. Import flight_fare_sales.csv here
--
-- The CSV is generated by:
-- python/04_generate_commercial_data.py
--
-- In pgAdmin:
--   Right-click flight_fare_sales
--   Select Import/Export Data
--   Select Import
--   Choose flight_fare_sales.csv
--   Enable Header
--   Set delimiter to comma
--
-- Do not import the file into flights_staging.
-- ------------------------------------------------------------


-- ------------------------------------------------------------
-- 4. Add constraints after the import
-- ------------------------------------------------------------

ALTER TABLE flight_fare_sales
ADD CONSTRAINT flight_fare_sales_primary_key
PRIMARY KEY (flight_id, fare_class);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT flight_fare_sales_flight_fk
FOREIGN KEY (flight_id)
REFERENCES commercial_flights (flight_id);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT valid_fare_class
CHECK (
    fare_class IN (
        'Economy',
        'Premium Economy',
        'Business'
    )
);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT nonnegative_seat_capacity
CHECK (seat_capacity >= 0);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT nonnegative_passengers
CHECK (passengers >= 0);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT passengers_within_capacity
CHECK (passengers <= seat_capacity);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT nonnegative_average_fare
CHECK (average_fare >= 0);


ALTER TABLE flight_fare_sales
ADD CONSTRAINT nonnegative_ticket_revenue
CHECK (ticket_revenue >= 0);


-- ------------------------------------------------------------
-- 5. Add indexes
-- ------------------------------------------------------------

CREATE INDEX idx_fare_sales_flight_id
ON flight_fare_sales (flight_id);

CREATE INDEX idx_fare_sales_fare_class
ON flight_fare_sales (fare_class);


-- ------------------------------------------------------------
-- 6. Update PostgreSQL query-planning statistics
-- ------------------------------------------------------------

ANALYZE flight_fare_sales;


-- ------------------------------------------------------------
-- 7. Validation
-- Expected number of rows:
-- 424,145 flights × 3 fare classes = 1,272,435
-- ------------------------------------------------------------

SELECT
    COUNT(*) AS total_sales_records,
    COUNT(DISTINCT flight_id) AS distinct_flights,
    COUNT(DISTINCT fare_class) AS fare_classes
FROM flight_fare_sales;


SELECT
    fare_class,
    SUM(passengers) AS passengers,
    ROUND(SUM(ticket_revenue), 2) AS revenue,
    ROUND(
        SUM(ticket_revenue) /
        NULLIF(SUM(passengers), 0),
        2
    ) AS weighted_average_fare
FROM flight_fare_sales
GROUP BY fare_class
ORDER BY fare_class;


SELECT
    COUNT(*) AS invalid_capacity_records
FROM flight_fare_sales
WHERE passengers > seat_capacity
   OR passengers < 0
   OR seat_capacity < 0;


SELECT
    COUNT(*) AS unmatched_flights
FROM flight_fare_sales AS ffs
LEFT JOIN commercial_flights AS cf
    ON ffs.flight_id = cf.flight_id
WHERE cf.flight_id IS NULL;