-- ============================================================
-- Airline Operations Analytics — Schema
-- ============================================================
-- Design notes:
--   * "flights" and "airports" are populated from real BTS
--     Reporting Carrier On-Time Performance data (2024).
--   * "aircraft" is generated/enriched (BTS doesn't publish
--     seat capacity), but keyed on real tail numbers.
--   * "customers", "bookings", "ticket_classes" are synthetic,
--     generated by the python/ scripts, but bookings reference
--     real flight_id values so downstream analysis (load factor,
--     revenue by route, etc.) is grounded in real operations.
-- ============================================================

DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS ticket_classes CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS aircraft CASCADE;
DROP TABLE IF EXISTS airports CASCADE;

-- ------------------------------------------------------------
-- Reference: airports
-- ------------------------------------------------------------
CREATE TABLE airports (
    airport_code    CHAR(3) PRIMARY KEY,      -- IATA code, e.g. 'BOS'
    airport_name    VARCHAR(150),
    city            VARCHAR(100),
    state           CHAR(2),
    latitude        NUMERIC(9,6),
    longitude       NUMERIC(9,6)
);

-- ------------------------------------------------------------
-- Reference: aircraft
-- ------------------------------------------------------------
CREATE TABLE aircraft (
    tail_number     VARCHAR(10) PRIMARY KEY,  -- e.g. 'N12345'
    manufacturer    VARCHAR(50),
    model           VARCHAR(50),
    seat_capacity   INTEGER,
    year_manufactured INTEGER
);

-- ------------------------------------------------------------
-- Core fact table: flights (real BTS data)
-- ------------------------------------------------------------
CREATE TABLE flights (
    flight_id               BIGSERIAL PRIMARY KEY,   -- surrogate key (BTS has none)
    flight_date             DATE NOT NULL,
    reporting_airline       VARCHAR(5) NOT NULL,     -- e.g. 'DL', 'AA', 'WN'
    flight_number           VARCHAR(10),
    tail_number             VARCHAR(10) REFERENCES aircraft(tail_number),
    origin                  CHAR(3) NOT NULL REFERENCES airports(airport_code),
    dest                    CHAR(3) NOT NULL REFERENCES airports(airport_code),

    crs_dep_time            SMALLINT,   -- scheduled, HHMM as integer
    dep_time                SMALLINT,   -- actual
    dep_delay_minutes       NUMERIC(6,1),

    crs_arr_time            SMALLINT,
    arr_time                SMALLINT,
    arr_delay_minutes       NUMERIC(6,1),

    cancelled               BOOLEAN DEFAULT FALSE,
    cancellation_code       CHAR(1),      -- A/B/C/D per BTS coding
    diverted                BOOLEAN DEFAULT FALSE,

    distance                NUMERIC(8,1), -- miles
    air_time                NUMERIC(6,1), -- minutes
    crs_elapsed_time        NUMERIC(6,1),
    actual_elapsed_time     NUMERIC(6,1)
);

-- ------------------------------------------------------------
-- Synthetic commercial data
-- ------------------------------------------------------------
CREATE TABLE ticket_classes (
    class_id        SMALLINT PRIMARY KEY,
    class_name      VARCHAR(30) NOT NULL,     -- Economy / Premium Economy / Business
    price_multiplier NUMERIC(4,2) NOT NULL    -- applied to base fare
);

CREATE TABLE customers (
    customer_id     BIGSERIAL PRIMARY KEY,
    first_name      VARCHAR(50),
    last_name       VARCHAR(50),
    email           VARCHAR(150),
    signup_date     DATE,
    loyalty_tier    VARCHAR(20) NOT NULL      -- Basic / Silver / Gold / Platinum
);

CREATE TABLE bookings (
    booking_id      BIGSERIAL PRIMARY KEY,
    flight_id       BIGINT NOT NULL REFERENCES flights(flight_id),
    customer_id     BIGINT NOT NULL REFERENCES customers(customer_id),
    class_id        SMALLINT NOT NULL REFERENCES ticket_classes(class_id),
    ticket_price    NUMERIC(8,2) NOT NULL,
    booking_date    DATE NOT NULL
);

-- ------------------------------------------------------------
-- Indexes (needed once flights hits several million rows)
-- ------------------------------------------------------------
CREATE INDEX idx_flights_date            ON flights(flight_date);
CREATE INDEX idx_flights_origin          ON flights(origin);
CREATE INDEX idx_flights_dest            ON flights(dest);
CREATE INDEX idx_flights_airline         ON flights(reporting_airline);
CREATE INDEX idx_flights_route           ON flights(origin, dest);
CREATE INDEX idx_flights_tail            ON flights(tail_number);

CREATE INDEX idx_bookings_flight         ON bookings(flight_id);
CREATE INDEX idx_bookings_customer       ON bookings(customer_id);
CREATE INDEX idx_bookings_class          ON bookings(class_id);

CREATE INDEX idx_customers_loyalty       ON customers(loyalty_tier);

-- ------------------------------------------------------------
-- Seed ticket_classes (static reference data)
-- ------------------------------------------------------------
INSERT INTO ticket_classes (class_id, class_name, price_multiplier) VALUES
    (1, 'Economy',          1.00),
    (2, 'Premium Economy',  1.45),
    (3, 'Business',         2.60);
